version: "3.7"
services:
  web:
    container_name: sf-postgresql13
    image: nimdasx/sf-postgresql13
    #restart: unless-stopped
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=gundamseed
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./varlibpostgresqldata:/var/lib/postgresql/data
